name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0-dev.2694+74f361a5c

      - name: Build
        run: zig build release -Doptimize=ReleaseFast

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: zig-out/bin/zon2tct-*
          generate_release_notes: true
